### ISSUE TITLE
[FEATURE] Revisit probe inclusion/exclusion logic

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#130] opened 2020-12-04 13:06 UTC
**Is your feature request related to a problem? Please describe.**
With the refactoring of the configuration that @simonwoolhouse is working on, and the new tag namespace that @iantivey is working on we should revisit how we include/exclude probes and scenarios from any specific run, using the new tag structure we're going to merge in.  By using tags we can also use a tag like `@beta` and include/exclude as necessary. 

The feature and scenario exclusions are also split apart in the configuration, so it's not intuitive.

**Describe the solution you'd like**
Use feature tags to define which features and scenarios will run, all configured in the same place, with justification at both levels if something is excluded.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by eddie-knight** [comment] 2020-12-09 17:18
Closing this as a duplicate of #91, copying these notes over there as a comment

**Closed by eddie-knight** 2020-12-09 17:18 UTC
Labels: feature request, probr core
