### ISSUE TITLE
[BUG] Static files are not found when running the debugger

### ISSUE THREAD

**Issue by simonwoolhouse** [citihub/probr#122] opened 2020-12-03 09:36 UTC
**Describe the bug**
Boxed static files are not found when running in Probr in the debugger
Low priority as outside the debugger, Probr runs ok

**To Reproduce**
Run in debugger. No feature files or yaml files are read causing no probes to be run successfully

A temp fix is to make the following changes:
Line 37 in service_packs.go: box := utils.BoxStaticFile(pack+p.Name(), "**../service_packs**", pack, p.Name())
Line 44 in kubernetes.go: AssetsDir = filepath.Join(**".."**, "service_packs", "kubernetes", "assets")

**Expected behavior**
Probr should run correctly in the debugger

**Screenshots**

**Additional context**

**Comment by eddie-knight** [comment] 2021-01-11 14:16
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/cmd/main.go",
            "env": {},
            "args": ["-varsfile=${workspaceFolder}/examples/config.yml", "-tags=@CIS-5.1.3", "-loglevel=NOTICE"]
        //    "args": ["-varsfile=${workspaceFolder}/examples/config.yml", "-loglevel=NOTICE"]
        }
    ]
}
```
For reference, this is my most recent version of the vs code debug file

**Comment by lcarrazana** [comment] 2021-01-13 21:36
I faced same issue when debugging:
_feature path "service_pack\storage\azure\access_whitelisting\access_whitelisting.feature" is not available_

I think the problem is the reference to static files uses relative paths, and VSCode debugger doesn't know how to resolve it by default.

I fixed it by setting the Current Working Directory ("cwd") in VS Code debug config:

```
# .vscode/launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch CMD with args",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${workspaceFolder}/cmd/main.go",
            "args": ["--varsfile", "${workspaceFolder}/examples/config.yml", "--loglevel", "WARN", "--tags", "@probes/storage/access_whitelisting/1.0"],
            "cwd": "${workspaceFolder}"
        }        
    ]
}
```


Reference: https://code.visualstudio.com/docs/editor/debugging

**Comment by eddie-knight** [comment] 2021-01-13 22:22
Closing this issue, as it appears to be resolved- thanks @lcarrazana!

**Closed by eddie-knight** 2021-01-13 22:22 UTC
Labels: bug, kubernetes, service pack
