### ISSUE TITLE
[FEATURE] Integration environment - Stable pass + Stable fail

### ISSUE THREAD

**Issue by lcarrazana** [citihub/probr#276] opened 2021-02-09 20:56 UTC
**Is your feature request related to a problem? Please describe.**
As part of Continuous Integration and to ensure product stability, we need to have pre-production environments to validate expected results for Pass and Fail. 

**Describe the solution you'd like**
- Provision a dev integration environment with two known configurations:
  - Settings in place to make probes fail - Stable Fail
  - Settings in places to make probes pass - Stable Pass
- We need to run probr often in this environment (if not on every PR), to catch integration issues as early as possible.

**Describe alternatives you've considered**
1. A fully automated pipeline
  - Provision infrastructure with Terraform
  - Run `probr` and save results
  - Destroy infrastructure

**Additional context**
N/A

**Comment by eddie-knight** [comment] 2021-02-17 16:57
closing as duplicate of #274

**Closed by eddie-knight** 2021-02-17 16:57 UTC
Labels: QA, feature request
