### ISSUE TITLE
[FEATURE] Re-factor configuration file

### ISSUE THREAD

**Issue by iantivey** [citihub/probr#96] opened 2020-11-24 12:10 UTC
**Is your feature request related to a problem? Please describe.**
The service pack configuration isn't fully contained under "Service Pack"

**Describe the solution you'd like**
```
ServicePacks:
   Kubernetes:
    Excluded: string
    KubeConfig: string
    KubeContext: string
    AuthorisedContainerRegistries: list<string>
    UnauthorisedContainerRegistries: list<string>
    ProbeRegistry: string
    ProbeImage: string
    Probes: list<Probe>
  StorageAccounts:
    Excluded: string
    Specific: string
    Pack: string    
    Config: string
    Probes: list<Probr>
  AnotherService:
    Excluded: string
    Specific: string
    Pack: string    
    Config: string
    Probes: list<Probr>
```

**Additional context**
As we add more service packs we need to make them as self contained as possible

**Comment by eddie-knight** [comment] 2020-11-25 12:23
Closing as a duplicate of #91 

Copied these suggestions over there with a reference to this issue :+1:

**Closed by eddie-knight** 2020-11-25 12:23 UTC
Labels: feature request
